### ISSUE TITLE
Comprehensive Testing Needed

### ISSUE THREAD

**Issue by nakraft** [SiddarthR56/spark#17]
## Summary

Testing is currently non-existent. Before merge to main, coverage must be completed. 

## Action Items 

*To split up testing fairly, the following testing areas have been developed. Please choose an area to complete* 

Black box tests should be created for the following: 
1) Testing ability to join a room and to exit room and join a different room. 
2) Testing ability for two participants to join a room together and see each others video. 
3) Testing capability for muting and unmute and turning on/off video. 
4) Testing ability to screen share. 
5) Testing ability to close software and disconnect from sockets. 

*Note: down the line testing will be needed for gesture recognition as well*

**Comment by nakraft** [comment]
Progress has been made. Final testing requirements to consider include: 
- gesture recognition 
- assertions for correct behavior at workflow 
- testing volume/screen share capabilities. 

Socket testing has been completed.

**Comment by Parth-25m** [comment]
Added gesture testing, uses pre-recorded data to test the gestures

**Comment by nakraft** [comment]
testing badge runs automated tests with every merge to main
