### ISSUE TITLE
Develop Screen Sharing Capabilities

### ISSUE THREAD

**Issue by nakraft** [SiddarthR56/spark#3]
## Summary

General server/client side has been implemented with interface between two parties. However, no opportunity exists for manipulation of the software (screen sharing, volume controls, message chats, etc). 

## Steps to reproduce

1) Start the application with npm start or node server.js. 
2) Navigate in finder to localhost:3000 and open in browser.
3) Enter any room number into the prompt bar.
4) Repeat steps 1-3 in a secondary browser.
5) Both browsers will see both video chats. 
6) Notice there is no other opportunities for additional manipulation. 

## Expected correct behavior

Both the user's video and the other people's video in the room should be displayed. 
Upon entering a room number, a web video interface should support other features that allows the user to know they have successfully entered the room. 

__ There should be a choice to share screen with another party __ This will support the further development of gesture recognition to control a powerpoint slide. 

## Next Steps

- Implement Screen Sharing capabilities
- Focus on ability to share powerpoint screen 
- Create 'on web interface' buttons to manipulate powerpoint slides (this will ensure easy tie into gesture recognition algorithm being developed)

**Comment by kanishkharde** [comment]
I added features that shows new users added and  i implemented the screen sharing but one issue i am facing is that the stream quality is not good its kinda blury and i am not able to integreate the screen feature.

**Comment by nakraft** [comment]
I found some resources that might help as a starting point: 
- https://mediasoup.discourse.group/t/want-to-increase-screen-share-resolution/2737/10
- https://stackoverflow.com/questions/57003258/webrtc-screen-sharing-quality-in-chrome

"You need to set incommingbitrate 1Mbp/s or higher for screen capture, but for experimenting, trial this…
maxIncomingBiterate at 2000000,
initialAvailableOutgoingBitrate at 320000

Because 2D/3D rendering have a major impact on resources it’s best to find this limit and cap your clients as tight as possible.

In client you should run in the options when calling screens,

video:{
width:1280
height:720
fps:30
}"
